services:
    # BasicEntities
    runroom_samples.basic_entities.admin.book:
        class: Runroom\SamplesBundle\BasicEntities\Admin\BookAdmin
        public: true
        arguments: [~, Runroom\SamplesBundle\BasicEntities\Entity\Book, Runroom\SortableBehaviorBundle\Controller\SortableAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Books' }

    runroom_samples.basic_entities.admin.category:
        class: Runroom\SamplesBundle\BasicEntities\Admin\CategoryAdmin
        public: true
        arguments: [~, Runroom\SamplesBundle\BasicEntities\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Categories' }

    # Forms
    runroom_samples.forms.admin.contact:
        class: Runroom\SamplesBundle\Forms\Admin\ContactAdmin
        public: true
        arguments: [~, Runroom\SamplesBundle\Forms\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Contacts' }
