services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Runroom\SamplesBundle\:
        resource: ../../*

    # BasicEntities
    Runroom\SamplesBundle\BasicEntities\Controller\:
        resource: ../../BasicEntities/Controller
        public: true
        tags: [controller.service_arguments]

    # Forms
    Runroom\SamplesBundle\Forms\Controller\:
        resource: ../../Forms/Controller
        public: true
        tags: [controller.service_arguments]
